*CONSTRAINED_LAGRANGE_IN_SOLID_EDGE
$#   slave    master     sstyp     mstyp     nquad     ctype     direc     mcoup

$#   start       end      pfac      fric    frcmin      norm   normtyp      damp

$#      cq      hmin      hmax     ileak     pleak   lcidpor     nvent  blockage

$#  iboxid   ipenchk   intforc   ialesof    lagmul    pfacmm      thkf    

$#      a1        b1        a2        b2        a3        b3  

