*CONTROL_IMPLICIT_SOLUTION
$#  nsolvr    ilimit    maxref     dctol     ectol     rctol     lstol    abstol
        12         6        12    1.0e-3    1.0e-2                       1.0e-20
$#   dnorm    diverg     istif   nlprint    nlnorm   d3itctl     cpchk
         1                             3         4         1          
$#  arcctl    arcdir    arclen    arcmth    arcdmp    arcpsi    arcalf    arctim
                                                                                
$#   lsmtd     lsdir      irad      srad      awgt      sred
         4                                                   