on:
  push:
    branches:
      - master

name: 'Release Vscode Plugin'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  publish:
    name: Publishing
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Publish to VSCode Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.PUBLISHER_TOKEN }}
      - name: Publish to Open VSX
        run: npx ovsx publish -p ${{ secrets.OPENVSX_KEY }}
